name: COGS
channels:
  - conda-forge  
dependencies:
  - gdal==3.2.0
  - awscli
  - numpy-stl
  - pip
  - pip:
    - fiona
    - matplotlib
    - rasterio
    - wget
    - pyproj
    - geopandas
    
